version: "3.3"

services:
    db:
        image: mdillon/postgis
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - back-tier

    nginx:
        ports:
            - 80:80

    frontend:

        environment:
            - NODE_ENV=development
            - HOST=http://localhost
    web:
        environment:
            - ARTSMAP_HOST=ratpack.sebastiantech.ca
            - ARTSMAP_DB=fpcc_artsmap_prod
            - ARTSMAP_USER=
            - ARTSMAP_PW=
            - FPLM_HOST=maps.fpcc.ca
            - FPLM_DB=fpmaps_d7_live
            - FPLM_USER=
            - FPLM_PW=


volumes:
    pg-data:
        driver: local

