# Generated by Django 2.2.8 on 2020-10-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def migrate_grant_categories(apps, schema_editor):
        Grant = apps.get_model('grants', 'Grant')
        GrantCategory = apps.get_model('grants', 'GrantCategory')
        
        def create_and_set_child_categories(parent_category, child_categories):
            order = 1
            for c in child_categories:
                # create category for child category
                category = GrantCategory.objects.create(
                    parent=parent_category,
                    order=order,
                    **c)
                order += 1

                # find grants based on child categories
                grants = Grant.objects.filter(grant__startswith=c.get('abbreviation'))
                for grant in grants:
                    if grant.grant.split(' ')[0] == c.get('abbreviation'):
                        grant.grant_category = category
                        grant.save()

        # create parent categories
        arts_category = GrantCategory.objects.create(
            name='Arts', abbreviation='Arts')
        heritage_category = GrantCategory.objects.create(
            name='Heritage', abbreviation='Heritage')
        language_category = GrantCategory.objects.create(
            name='Language', abbreviation='Language')

        arts_child_categories = [
            {
                'abbreviation': 'ARTS',
                'name': 'Arts One Time Grant'
            },
            {
                'abbreviation': 'AIND',
                'name': 'Individual Artists Grant'
            },
            {
                'abbreviation': 'ASHR',
                'name': 'Sharing Traditional Arts Grant'
            },
            {
                'abbreviation': 'AORG',
                'name': 'Organizations and Collectives Grant'
            },
            {
                'abbreviation': 'AADM',
                'name': 'Arts Administration Internships Grant'
            },
            {
                'abbreviation': 'AAYEA',
                'name': 'Aboriginal Youth Engaged in the Arts Grant'
            },
            {
                'abbreviation': 'AMIC',
                'name': 'Arts Micro Grants'
            },
            {
                'abbreviation': 'ALND',
                'name': 'Community Land Based Arts Grant'
            },
            {
                'abbreviation': 'AEMIP',
                'name': 'Emerging Music Industry Professionals Grant'
            },
            {
                'abbreviation': 'AECMR',
                'name': 'Expanding Capacity in the Indigenous Music Recording Industry Grant'
            },
            {
                'abbreviation': 'ATPMP',
                'name': 'Touring, Promotion/Marketing and Performance Grant'
            }
        ]
        heritage_child_categories = [
            {
                'abbreviation': 'HMIC',
                'name': 'Indigenous Heritage Micro Grant'
            },
            {
                'abbreviation': 'HSOP',
                'name': 'Sense of Place Grant'
            }
        ]
        language_child_categories = [
            {
                'abbreviation': 'LALI',
                'name': 'Aboriginal Languages Initiative'
            },
            {
                'abbreviation': 'LBCLI',
                'name': 'BC Language Initiative'
            },
            {
                'abbreviation': 'LDIGI',
                'name': 'Digitization Program'
            },
            {
                'abbreviation': 'LFV',
                'name': 'FirstVoices Program'
            },
            {
                'abbreviation': 'LILG',
                'name': 'Indigenous Languages Grant'
            },
            {
                'abbreviation': 'LANG',
                'name': 'Language One Time Grant'
            },
            {
                'abbreviation': 'LLN',
                'name': 'Language Nest Program'
            },
            {
                'abbreviation': 'LLRPP',
                'name': 'Language Revitalization Planning Program'
            },
            {
                'abbreviation': 'LMAP',
                'name': 'Mentor-Apprentice Program'
            },
            {
                'abbreviation': 'LPATH',
                'name': 'Pathways to Language Vitality Program'
            },
            {
                'abbreviation': 'LRML',
                'name': 'Reclaiming My Language Program'
            },
            {
                'abbreviation': 'LTECH',
                'name': 'Language Technology Program'
            },
            {
                'abbreviation': 'LYES',
                'name': 'Youth Empowered Speakers Program'
            },
        ]

        create_and_set_child_categories(arts_category, arts_child_categories)
        create_and_set_child_categories(heritage_category, heritage_child_categories)
        create_and_set_child_categories(language_category, language_child_categories)


    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('abbreviation', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='grants.GrantCategory')),
            ],
            options={
                'verbose_name_plural': 'Grant Categories',
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.GrantCategory'),
        ),
        # migrations.RunPython(migrate_grant_categories),
        migrations.RemoveField(
            model_name='grant',
            name='category',
        ),
    ]
