# Generated by Django 2.2.4 on 2019-08-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0058_auto_20190825_0418'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='communities',
            field=models.ManyToManyField(to='language.Community'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(to='language.Language'),
        ),
    ]
