# Generated by Django 2.2.4 on 2019-08-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0061_auto_20190828_0658'),
        ('users', '0002_auto_20190827_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='community',
        ),
        migrations.AddField(
            model_name='user',
            name='communities',
            field=models.ManyToManyField(to='language.Community'),
        ),
    ]
