# Generated by Django 2.2.4 on 2019-08-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190828_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='communities',
        ),
    ]
