# Generated by Django 2.2.4 on 2019-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_notification_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
