# Generated by Django 2.2.8 on 2020-04-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfileClaimRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_profile_email', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('is_claimed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
