# Generated by Django 2.2.8 on 2020-05-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200428_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileClaimRecord',
        ),
    ]
