# Generated by Django 2.2.8 on 2020-06-24 10:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='non_bc_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, null=True, size=None),
        ),
    ]
