# Generated by Django 2.2.8 on 2020-07-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_artist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artist_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.PlaceName'),
        ),
    ]
