# Generated by Django 2.2.13 on 2022-07-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200714_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_community',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
