# Generated by Django 2.2.3 on 2019-07-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20190705_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagesubfamily',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.LanguageFamily'),
        ),
    ]
