# Generated by Django 2.2.3 on 2019-07-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_languagesubfamily_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='sub_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.LanguageSubFamily'),
        ),
    ]
