# Generated by Django 2.2.3 on 2019-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_language_sub_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
