# Generated by Django 2.2.3 on 2019-07-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0005_language_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='email',
            field=models.EmailField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Language'),
        ),
        migrations.AddField(
            model_name='community',
            name='website',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
    ]
