# Generated by Django 2.2.3 on 2019-07-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0006_auto_20190705_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='english_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
