# Generated by Django 2.2.3 on 2019-07-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0010_auto_20190705_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placename',
            name='text',
        ),
        migrations.AddField(
            model_name='champion',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='champion',
            name='community',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Community'),
        ),
        migrations.AddField(
            model_name='champion',
            name='job',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='champion',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Language'),
        ),
        migrations.AddField(
            model_name='placename',
            name='other_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
