# Generated by Django 2.2.3 on 2019-07-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0011_auto_20190705_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialect',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.Language'),
        ),
    ]
