# Generated by Django 2.2.3 on 2019-07-05 21:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0012_dialect_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='language',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='community',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='placename',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
