# Generated by Django 2.2.3 on 2019-07-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0013_auto_20190705_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='point',
        ),
    ]
