# Generated by Django 2.2.3 on 2019-07-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0014_remove_champion_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='kind',
            field=models.CharField(default='', max_length=15),
        ),
    ]
