# Generated by Django 2.2.3 on 2019-07-12 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0017_communitylink'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(default=None, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.Language')),
            ],
        ),
    ]
