# Generated by Django 2.2.3 on 2019-07-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0018_languagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
