# Generated by Django 2.2.3 on 2019-07-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0019_community_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitylink',
            old_name='website',
            new_name='url',
        ),
    ]
