# Generated by Django 2.2.3 on 2019-07-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0021_auto_20190712_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='LNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='language',
        ),
        migrations.AddField(
            model_name='community',
            name='language',
            field=models.ManyToManyField(to='language.Language'),
        ),
        migrations.CreateModel(
            name='LNAData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluent_speakers', models.IntegerField()),
                ('some_speakers', models.IntegerField()),
                ('learners', models.IntegerField()),
                ('pop_off_res', models.IntegerField()),
                ('pop_on_res', models.IntegerField()),
                ('pop_total_value', models.IntegerField()),
                ('lna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.LNA')),
            ],
        ),
        migrations.AddField(
            model_name='lna',
            name='nations',
            field=models.ManyToManyField(to='language.Community'),
        ),
    ]
