# Generated by Django 2.2.3 on 2019-07-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0023_auto_20190714_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lna',
            name='nations',
        ),
        migrations.AddField(
            model_name='lnadata',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Community'),
        ),
    ]
