# Generated by Django 2.2.3 on 2019-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0024_auto_20190714_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='lna',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lnadata',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
