# Generated by Django 2.2.3 on 2019-07-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0026_auto_20190714_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='fluent_speakers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='learners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='pop_total_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='some_speakers',
            field=models.IntegerField(default=0),
        ),
    ]
