# Generated by Django 2.2.3 on 2019-07-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0027_auto_20190714_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='lna',
            name='year',
            field=models.IntegerField(default=1970),
        ),
    ]
