# Generated by Django 2.2.3 on 2019-07-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0031_auto_20190716_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='color',
            field=models.CharField(max_length=31),
        ),
    ]
