# Generated by Django 2.2.3 on 2019-07-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0032_auto_20190716_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='regions',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='regions',
            field=models.CharField(default='', max_length=255),
        ),
    ]
