# Generated by Django 2.2.3 on 2019-07-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0033_auto_20190722_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnadata',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lnadata',
            name='nest_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lnadata',
            name='num_schools',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lnadata',
            name='oece_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lnadata',
            name='school_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='placename',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='community',
            name='alt_phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='english_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='internet_speed',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='community',
            name='other_names',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='regions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='website',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='other_names',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='regions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
