# Generated by Django 2.2.3 on 2019-07-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0034_auto_20190725_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='sleeping',
            field=models.BooleanField(default=False),
        ),
    ]
