# Generated by Django 2.2.3 on 2019-07-27 23:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0035_language_sleeping'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='language',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='language',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
