# Generated by Django 2.2.3 on 2019-07-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0036_auto_20190727_2353'),
        ('language', '0033_art'),
    ]

    operations = [
    ]
