# Generated by Django 2.2.4 on 2019-08-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0038_auto_20190801_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='sub_family',
        ),
        migrations.AddField(
            model_name='language',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.LanguageFamily'),
        ),
        migrations.DeleteModel(
            name='LanguageSubFamily',
        ),
    ]
