# Generated by Django 2.2.4 on 2019-08-09 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0039_auto_20190809_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagefamily',
            name='color',
            field=models.CharField(default='RGB(0.5,0.5,0.5)', max_length=31),
        ),
        migrations.AlterField(
            model_name='language',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.LanguageFamily'),
        ),
    ]
