# Generated by Django 2.2.4 on 2019-08-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0040_auto_20190809_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placename',
            old_name='other_name',
            new_name='other_names',
        ),
    ]
