# Generated by Django 2.2.4 on 2019-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0043_auto_20190814_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendent'), ('AP', 'Aproved'), ('DE', 'Declined')], default='PE', max_length=2),
        ),
    ]
