# Generated by Django 2.2.4 on 2019-08-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0044_placename_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendent'), ('VE', 'Verified'), ('RE', 'Rejected')], default='PE', max_length=2),
        ),
    ]
