# Generated by Django 2.2.4 on 2019-08-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0045_auto_20190814_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendent'), ('VE', 'Verified'), ('RE', 'Rejected')], default=None, max_length=2),
        ),
    ]
