# Generated by Django 2.2.4 on 2019-08-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0046_auto_20190814_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placename',
            name='status',
        ),
    ]
