# Generated by Django 2.2.4 on 2019-08-15 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0048_placename_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='placename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='language.PlaceName'),
        ),
    ]
