# Generated by Django 2.2.4 on 2019-08-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0049_auto_20190815_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='status',
            field=models.CharField(choices=[('FL', 'Flagged'), ('VE', 'Verified')], default=None, max_length=2, null=True),
        ),
    ]
