# Generated by Django 2.2.4 on 2019-08-18 19:12

from django.db import migrations, models

# rename dups.
def forwards(apps, schema_editor):
    PlaceName = apps.get_model("language", "PlaceName")
    names = {}
    for p in PlaceName.objects.all():
        if p.name in names:
            p.name += " Copy"
            p.save()
        names[p.name] = 1


class Migration(migrations.Migration):

    dependencies = [("language", "0051_auto_20190816_1817")]

    operations = [
        migrations.RunPython(forwards),
        migrations.RemoveField(model_name="placename", name="traditional_name"),
        migrations.AddField(
            model_name="community",
            name="mapped_spellings",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="language",
            name="mapped_spellings",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="placename",
            name="mapped_spellings",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="champion",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="community",
            name="other_names",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="communitylanguagestats",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="dialect",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="other_names",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="languagefamily",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="lna",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="lnadata",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="placename",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="placenamecategory",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
