# Generated by Django 2.2.4 on 2019-08-19 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0052_communitymember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitymember',
            options={'verbose_name_plural': 'Community Members'},
        ),
        migrations.AlterModelOptions(
            name='placenamecategory',
            options={'verbose_name_plural': 'Place name Categories'},
        ),
        migrations.AddField(
            model_name='languagemember',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.Language'),
        ),
    ]
