# Generated by Django 2.2.4 on 2019-08-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0052_auto_20190818_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=255)),
                ('recorder', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_recorded', models.DateField(verbose_name='date recorded')),
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='mapped_spellings',
        ),
        migrations.RemoveField(
            model_name='language',
            name='mapped_spellings',
        ),
        migrations.RemoveField(
            model_name='placename',
            name='mapped_spellings',
        ),
        migrations.AddField(
            model_name='community',
            name='fv_archive_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='community',
            name='fv_guid',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='community',
            name='population_off_reserve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='population_on_reserve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='avg_hrs_wk_languages_in_ece',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='avg_hrs_wk_languages_in_language_nests',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='avg_hrs_wk_languages_in_school',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='community_adult_language_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='ece_programs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='fv_guid',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='language',
            name='language_nests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='total_schools',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='color',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AddField(
            model_name='community',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Recording'),
        ),
        migrations.AddField(
            model_name='language',
            name='greeting_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greeting_languages', to='language.Recording'),
        ),
        migrations.AddField(
            model_name='language',
            name='language_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='language.Recording'),
        ),
    ]
