# Generated by Django 2.2.4 on 2019-08-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0053_auto_20190818_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='communitylanguagestats',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='dialect',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='languagefamily',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='lna',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='lnadata',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='placename',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.AlterField(
            model_name='placenamecategory',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
    ]
