# Generated by Django 2.2.4 on 2019-08-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0054_auto_20190818_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitylanguagestats',
            options={},
        ),
        migrations.RemoveField(
            model_name='communitylanguagestats',
            name='created',
        ),
        migrations.RemoveField(
            model_name='communitylanguagestats',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='communitylanguagestats',
            name='name',
        ),
        migrations.AddField(
            model_name='communitylanguagestats',
            name='active_learners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitylanguagestats',
            name='fluent_speakers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitylanguagestats',
            name='semi_speakers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='communitylanguagestats',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.Community'),
        ),
        migrations.AlterField(
            model_name='communitylanguagestats',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.Language'),
        ),
    ]
