# Generated by Django 2.2.4 on 2019-08-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0055_auto_20190818_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitylanguagestats',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Community'),
        ),
        migrations.AlterField(
            model_name='communitylanguagestats',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language'),
        ),
    ]
