# Generated by Django 2.2.4 on 2019-08-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0056_auto_20190818_2026'),
        ('language', '0054_mediafavourite'),
    ]

    operations = [
    ]
