# Generated by Django 2.2.4 on 2019-08-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0057_merge_20190819_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagemember',
            name='language',
        ),
        migrations.RemoveField(
            model_name='languagemember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mediafavourite',
            name='user',
        ),
        migrations.AlterField(
            model_name='mediafavourite',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Traditional Name'),
        ),
        migrations.DeleteModel(
            name='CommunityMember',
        ),
        migrations.DeleteModel(
            name='LanguageMember',
        ),
    ]
