# Generated by Django 2.2.4 on 2019-08-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0059_mediafavourite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafavourite',
            name='user',
        ),
    ]
