# Generated by Django 2.2.4 on 2019-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0061_communitymember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='status',
            field=models.CharField(choices=[('UN', 'Unverified'), ('VE', 'Verified'), ('RE', 'Rejected')], default='UN', max_length=2),
        ),
    ]
