# Generated by Django 2.2.4 on 2019-08-28 07:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0061_auto_20190828_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, null=True, srid=4326),
        ),
    ]
