# Generated by Django 2.2.4 on 2019-08-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0062_auto_20190827_1906'),
        ('language', '0060_remove_mediafavourite_user'),
    ]

    operations = [
    ]
