# Generated by Django 2.2.4 on 2019-08-28 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0062_placename_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placename',
            name='community',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Community'),
        ),
        migrations.AlterField(
            model_name='placename',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Language'),
        ),
        migrations.AlterField(
            model_name='placename',
            name='status',
            field=models.CharField(choices=[('UN', 'Unverified'), ('FL', 'Flagged'), ('VE', 'Verified')], default=None, max_length=2, null=True),
        ),
    ]
