# Generated by Django 2.2.4 on 2019-08-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0062_auto_20190827_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='language_admins',
            field=models.ManyToManyField(to='language.LanguageMember'),
        ),
    ]
