# Generated by Django 2.2.4 on 2019-08-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0063_community_language_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='community',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.Community'),
        ),
        migrations.AddField(
            model_name='placename',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.Language'),
        ),
    ]
