# Generated by Django 2.2.4 on 2019-08-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0063_auto_20190828_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('RA', 'Community Admin'), ('RM', 'Community Member')], default='RM', max_length=2),
        ),
        migrations.AlterField(
            model_name='placename',
            name='status',
            field=models.CharField(choices=[('UN', 'Unverified'), ('FL', 'Flagged'), ('VE', 'Verified')], default='UN', max_length=2, null=True),
        ),
    ]
