# Generated by Django 2.2.4 on 2019-11-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0063_merge_20190828_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='nation_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='LanguageMember',
        ),
    ]
