# Generated by Django 2.2.4 on 2019-08-28 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0066_auto_20190828_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='media',
        ),
        migrations.AddField(
            model_name='favourite',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.PlaceName'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
