# Generated by Django 2.2.4 on 2019-08-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0067_auto_20190828_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placename',
            name='polygon',
        ),
    ]
