# Generated by Django 2.2.4 on 2019-08-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0067_auto_20190828_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='status_reason',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
