# Generated by Django 2.2.4 on 2019-08-29 21:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0069_auto_20190829_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, null=True, srid=4326),
        ),
    ]
