# Generated by Django 2.2.4 on 2019-08-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0070_auto_20190829_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placenamecategory',
            name='icon_name',
            field=models.CharField(blank=True, default=None, help_text='Name of the icon in MapBox', max_length=32),
        ),
    ]
