# Generated by Django 2.2.4 on 2019-08-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0068_placename_status_reason'),
        ('language', '0071_auto_20190831_1842'),
    ]

    operations = [
    ]
