# Generated by Django 2.2.4 on 2019-09-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0072_merge_20190831_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='audio_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='placename',
            name='audio_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
