# Generated by Django 2.2.4 on 2019-09-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0074_auto_20190906_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
    ]
