# Generated by Django 2.2.4 on 2019-09-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0075_auto_20190906_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('UN', 'Unverified'), ('FL', 'Flagged'), ('VE', 'Verified')], default='UN', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='status_reason',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
