# Generated by Django 2.2.4 on 2019-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0076_auto_20190907_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
