# Generated by Django 2.2.4 on 2019-09-10 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0077_auto_20190909_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='community',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='language.Community'),
        ),
    ]
