# Generated by Django 2.2.4 on 2019-09-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0079_auto_20190910_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('UN', 'Unverified'), ('FL', 'Flagged'), ('VE', 'Verified'), ('RE', 'Rejected')], default='UN', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='placename',
            name='status',
            field=models.CharField(choices=[('UN', 'Unverified'), ('FL', 'Flagged'), ('VE', 'Verified'), ('RE', 'Rejected')], default='UN', max_length=2, null=True),
        ),
    ]
