# Generated by Django 2.2.4 on 2019-09-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0080_auto_20190911_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
