# Generated by Django 2.2.4 on 2019-09-13 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0081_auto_20190911_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='community',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='language.Community'),
        ),
    ]
