# Generated by Django 2.2.4 on 2019-09-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0082_media_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='favourite_type',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
