# Generated by Django 2.2.4 on 2019-09-17 03:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0083_auto_20190916_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='favourite',
            name='zoom',
            field=models.IntegerField(default=0),
        ),
    ]
