# Generated by Django 2.2.4 on 2019-09-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0085_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='community_only',
            field=models.BooleanField(null=True),
        ),
    ]
