# Generated by Django 2.2.4 on 2019-09-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0086_media_community_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name_plural': 'Communities'},
        ),
    ]
