# Generated by Django 2.2.4 on 2019-10-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0089_auto_20191014_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
