# Generated by Django 2.2.4 on 2019-10-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0089_auto_20191014_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
