# Generated by Django 2.2.4 on 2019-10-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0090_recording_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
