# Generated by Django 2.2.4 on 2019-10-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0091_recording_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='location',
        ),
    ]
