# Generated by Django 2.2.4 on 2019-11-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0092_remove_recording_location'),
        ('language', '0090_auto_20191023_0832'),
    ]

    operations = [
    ]
