# Generated by Django 2.2.4 on 2019-11-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0094_community_nation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.Recording'),
        ),
    ]
