# Generated by Django 2.2.8 on 2020-03-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0097_auto_20200312_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_artwork',
            field=models.BooleanField(default=False),
        ),
    ]
