# Generated by Django 2.2.8 on 2020-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0098_media_is_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mime_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
