# Generated by Django 2.2.8 on 2020-03-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0099_media_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mime_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
