# Generated by Django 2.2.8 on 2020-03-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0100_auto_20200313_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='is_art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placename',
            name='node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placename',
            name='node_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
