# Generated by Django 2.2.8 on 2020-03-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0101_auto_20200316_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
