# Generated by Django 2.2.8 on 2020-03-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0105_artartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicArtArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_arts', to='language.PlaceName')),
                ('public_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_artists', to='language.PlaceName')),
            ],
        ),
        migrations.DeleteModel(
            name='ArtArtist',
        ),
    ]
