# Generated by Django 2.2.8 on 2020-03-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0107_placenametaxonomy_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='taxonomies',
            field=models.ManyToManyField(through='language.PlaceNameTaxonomy', to='language.Taxonomy'),
        ),
    ]
