# Generated by Django 2.2.8 on 2020-03-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0110_placename_public_arts'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='artists',
            field=models.ManyToManyField(related_name='_placename_artists_+', through='language.PublicArtArtist', to='language.PlaceName'),
        ),
        migrations.AlterField(
            model_name='placename',
            name='public_arts',
            field=models.ManyToManyField(related_name='_placename_public_arts_+', through='language.PublicArtArtist', to='language.PlaceName'),
        ),
    ]
