# Generated by Django 2.2.8 on 2020-03-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0111_auto_20200325_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('-id',)},
        ),
    ]
