# Generated by Django 2.2.8 on 2020-03-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0112_auto_20200326_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=100)),
                ('placename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_data', to='language.PlaceName')),
            ],
        ),
    ]
