# Generated by Django 2.2.8 on 2020-03-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0113_relateddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateddata',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
    ]
