# Generated by Django 2.2.8 on 2020-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0115_auto_20200409_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateddata',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
