# Generated by Django 2.2.8 on 2020-04-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0116_relateddata_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateddata',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
