# Generated by Django 2.2.8 on 2020-04-28 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0118_auto_20200414_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_placenames', to=settings.AUTH_USER_MODEL),
        ),
    ]
