# Generated by Django 2.2.8 on 2020-05-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0120_remove_placename_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='order',
            field=models.IntegerField(default=None, help_text='Value that determines the ordering of taxonomy. The lower the value is, the higher it is on the list', null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_taxonomies', to='language.Taxonomy'),
        ),
    ]
