# Generated by Django 2.2.8 on 2020-06-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0124_auto_20200530_0919'),
        ('language', '0097_auto_20200602_1042'),
    ]

    operations = [
    ]
