# Generated by Django 2.2.8 on 2020-06-09 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0097_auto_20200603_1311'),
        ('language', '0125_merge_20200602_1249'),
    ]

    operations = [
    ]
