# Generated by Django 2.2.8 on 2020-06-09 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0126_merge_20200609_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
