# Generated by Django 2.2.8 on 2020-06-16 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0127_auto_20200609_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placename',
            name='category',
        ),
        migrations.DeleteModel(
            name='PlaceNameCategory',
        ),
    ]
