# Generated by Django 2.2.8 on 2020-06-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0128_auto_20200616_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
