# Generated by Django 2.2.8 on 2020-07-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0130_placename_non_bc_languages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lna',
            options={'verbose_name_plural': 'LNA'},
        ),
        migrations.AlterModelOptions(
            name='lnadata',
            options={'verbose_name_plural': 'LNA Data'},
        ),
        migrations.AlterModelOptions(
            name='placename',
            options={'verbose_name_plural': 'Place Names'},
        ),
        migrations.AlterModelOptions(
            name='placenametaxonomy',
            options={'verbose_name_plural': 'Place Name Taxonomies'},
        ),
        migrations.AlterModelOptions(
            name='relateddata',
            options={'verbose_name_plural': 'Related Data'},
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name_plural': 'Taxonomies'},
        ),
        migrations.AddField(
            model_name='placename',
            name='other_community',
            field=models.CharField(default='', max_length=64),
        ),
    ]
