# Generated by Django 2.2.8 on 2020-07-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0131_auto_20200709_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='other_community',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
