# Generated by Django 2.2.8 on 2020-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0132_auto_20200709_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='other_community',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
