# Generated by Django 2.2.8 on 2020-10-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0133_auto_20200714_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='kind',
            field=models.CharField(choices=[('public_art', 'Public Art'), ('organization', 'Organization'), ('artist', 'Artist'), ('event', 'Event'), ('resource', 'Resource'), ('grant', 'Grant'), ('poi', 'Point of Interest')], default='', max_length=20),
        ),
    ]
