# Generated by Django 2.2.13 on 2022-05-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0134_auto_20201005_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='relateddata',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
