# Generated by Django 2.2.13 on 2022-07-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0136_communitymember_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='date_verified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
