# Generated by Django 2.2.13 on 2023-01-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    def migrate_community_to_m2m(apps, schema_editor):
        PlaceName = apps.get_model('language', 'PlaceName')

        placenames = PlaceName.objects.all()

        for placename in placenames:
            if placename.community:
                placename.communities.add(placename.community)
                placename.save()

    dependencies = [
        ('language', '0137_communitymember_date_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='communities',
            field=models.ManyToManyField(
                default=None, related_name='places', to='language.Community'),
        ),
        migrations.RunPython(migrate_community_to_m2m),
        migrations.RemoveField(
            model_name='placename',
            name='community',
        ),
    ]
