# Generated by Django 2.2.13 on 2023-03-08 06:53

from django.db import migrations, models
from web.constants import POI


class Migration(migrations.Migration):
    def fix_placename_kind(apps, schema_editor):
        PlaceName = apps.get_model('language', 'PlaceName')

        placenames = PlaceName.objects.all()

        for placename in placenames:
            if not placename.kind:
                placename.kind = POI
                placename.save()

    dependencies = [
        ('language', '0138_auto_20230110_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='kind',
            field=models.CharField(choices=[('public_art', 'Public Art'), ('organization', 'Organization'), ('artist', 'Artist'), (
                'event', 'Event'), ('resource', 'Resource'), ('grant', 'Grant'), ('poi', 'Point of Interest')], default='poi', max_length=20),
        ),
        migrations.RunPython(fix_placename_kind),
    ]
