# Generated by Django 2.2.13 on 2023-07-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    def migrate_event_date(apps, schema_editor):
        RelatedData = apps.get_model('language', 'RelatedData')
        
        for data in RelatedData.objects.filter(data_type="Event Date"):
            data.data_type = "event_date"
            data.save()

    dependencies = [
        ('language', '0139_auto_20230308_0653'),
    ]

    operations = [
        migrations.RunPython(migrate_event_date, reverse_code=migrations.RunPython.noop),
    ]
