# Generated by Django 2.2.13 on 2023-08-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0140_migrate_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='communities',
            field=models.ManyToManyField(blank=True, default=None, related_name='places', to='language.Community'),
        ),
    ]
