# Generated by Django 2.2.13 on 2023-11-13 06:27

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0141_auto_20230811_0256"),
    ]

    operations = [UnaccentExtension()]
