# Generated by Django 5.2 on 2026-07-30 23:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0143_communitymember_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitylanguagestats',
            options={'verbose_name_plural': 'Community Language Stats'},
        ),
        migrations.AlterField(
            model_name='placename',
            name='artists',
            field=models.ManyToManyField(related_name='artists+', through='language.PublicArtArtist', through_fields=('public_art', 'artist'), to='language.placename'),
        ),
        migrations.AlterField(
            model_name='placename',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Use https://geojson.io/ for manually creating geometry', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='placename',
            name='public_arts',
            field=models.ManyToManyField(related_name='public_arts+', through='language.PublicArtArtist', through_fields=('artist', 'public_art'), to='language.placename'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='order',
            field=models.IntegerField(blank=True, default=None, help_text='Value that determines the ordering of taxonomy.The lower the value is, the higher it is on the list', null=True),
        ),
    ]
