# Generated by Django 2.2.3 on 2019-08-01 18:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('art_type', models.CharField(default='', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('node_id', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
