# Generated by Django 2.2.3 on 2019-08-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='title',
        ),
        migrations.AddField(
            model_name='art',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
