# Generated by Django 2.2.3 on 2019-08-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_auto_20190801_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_type',
            field=models.CharField(default='', max_length=15),
        ),
    ]
