# Generated by Django 2.2.4 on 2019-08-12 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_auto_20190801_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
    ]
