# Generated by Django 2.2.4 on 2019-08-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_auto_20190812_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
