# Generated by Django 2.2.13 on 2021-11-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0007_artcategory_artist_artistaward_artistlink_artistmedia_association'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Art',
        ),
        migrations.DeleteModel(
            name='ArtCategory',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='artistaward',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistlink',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistmedia',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Association',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='ArtistAward',
        ),
        migrations.DeleteModel(
            name='ArtistLink',
        ),
        migrations.DeleteModel(
            name='ArtistMedia',
        ),
    ]
